# todo: define liveness, readiness probe tpl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.depl.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repo }}
          resources:
            {{- toYaml .Values.pod.resources | nindent 12 }}
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: atest-config
                  key: MESSAGE
            - name: PRIVATE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: atest-secret
                  key: PRIVATE_MESSAGE
                  optional: false
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: 3000 # thay port bằng value
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000 # thay port bằng value
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 8

          
