# todo: define liveness, readiness probe tpl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.depl.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repo }}
          resources:
            {{- toYaml .Values.depl.resources | nindent 12 }}
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: atest-config
                  key: MESSAGE
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: atest-secret
                  key: PRIVATE_MESSAGE
                  optional: false
