apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  labels:
    app: {{ .Values.image.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.podPort }}
  selector:
    app: {{ .Values.image.name }}