image:
  # ingress name -> service name -> deployment name -> pod name, container name
  # SA name
  name: defaultImg
  repo: gcr.io # must be replace by cmd
  tag: ""

# deployment
depl:
  replicaCount: 1
  resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true # create?
  name: defaultsa # annotation.name = "default"
  annotations: {}

service:
  type: ClusterIP
  port: 80
  podPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: atest.local
      paths:
        - path: /
          pathType: ImplementationSpecific