gke:
  projectId: "thetan-staging"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 30
  cpuPercent: 80
  memPercent: 80

# pod
pod:
  resources:
    requests:
      cpu: 32m
      memory: 256Mi