image:
  # ingress name -> service name -> deployment name -> pod name, container name
  # SA name
  # autoscaler -> deployment
  name: defaultimg
  repo: gcr.io # must be replace by cmd
  tag: ""

# deployment
depl:
  replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpuPercent: 80
  memPercent: 80

pod:
  

serviceAccount:
  enabled: true # create?
  name: defaultsa # annotation.name = "default"
  annotations: {}

service:
  enabled: true
  type: ClusterIP
  port: 80
  podPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: atest.staging.thetanarena.com
      paths:
        - path: /
          pathType: Prefix