{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "atestchart.gkeAnnotations" . | indent 4 }}
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Values.image.name }}
{{- end }}