name: redis staging

on: 
  push:
    branches: [redis]
  workflow_dispatch:


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: thetan-test
  GKE_ZONE: asia-southeast1-a 
  
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # setup gcloud cli
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Setup docker authentication
        run: gcloud --quiet auth configure-docker

      # Get k8s credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{env.GKE_CLUSTER}}
          location: ${{env.GKE_ZONE}}
          credentials: ${{secrets.GKE_SA_KEY}}

      # helm cli
      - name: Helm CLI
        uses: azure/setup-helm@v1

      - name: GCP Env
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Check Helm
        run: |-
          helm repo list 

      - name: Add binami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      # Deploy
      - name: Deploy
        run: |-
          helm upgrade --install redis-server bitnami/redis \
          -f ./redisautochart/values.yaml 
    
