name: test-server staging v2

on: 
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: thetan-test
  GKE_ZONE: asia-southeast1-a 
  IMAGE: atest
  
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # setup gcloud cli
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Setup docker authentication
        run: gcloud --quiet auth configure-docker 

      # Get k8s credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{env.GKE_CLUSTER}}
          location: ${{env.GKE_ZONE}}
          credentials: ${{secrets.GKE_SA_KEY}}

      # image
      - name: Build image
        run: |-
          docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
      
      - name: Store image
        run: docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      # helm cli
      - name: Helm CLI
        uses: azure/setup-helm@v1

      - name: GCP Env
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Deploy
      - name: Deploy
        run: |-
          helm upgrade --install --debug $IMAGE $CHART \
          --set image.repo=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --set image.name=$IMAGE \
          -f ./atestchart/values-base.yaml \
          -f ./atestchart/values-staging.yaml 
        env:
          CHART: oci://asia-southeast1-docker.pkg.dev/thetan-staging/test-charts/atestchart
    
