name: test-server staging

on: 
  workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: thetan-test
  GKE_ZONE: asia-southeast1-a 
  DEPLOYMENT_NAME: atest 
  IMAGE: static-site 
  
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # setup gcloud cli
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Setup docker authentication
        run: gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{env.GKE_CLUSTER}}
          location: ${{env.GKE_ZONE}}
          credentials: ${{secrets.GKE_SA_KEY}}

      - name: Build image
        run: docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
      
      - name: Store image
        run: docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Deploy
        run: |-
          helm upgrade $PROJECT_ID $PROJECT_ID-cluster/ \
          --set randocats.image.tag=$GITHUB_SHA \
          --wait
